name: Gh Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Plan
        uses: denis256/tg-gh-action@v0.0.5
        with:
          tf_version: '1.4.6'
          tg_version: 'latest'
          tg_dir: 'terragrunt-init-each-time'
          tg_command: run-all plan

      - name: Apply
        uses: denis256/tg-gh-action@v0.0.5
        with:
          tf_version: '1.4.6'
          tg_version: 'latest'
          tg_dir: 'terragrunt-init-each-time'
          tg_command: run-all apply

